// lib/mock-data.ts
export const dashboardMock = {
  player: {
    name: "Aether Fang",
    zodiac: "Scorpio",
    archetype: "Shadow Duelist",
    rarity: "Mythic",
    level: 12,
    xp: 780,
    xpToNext: 1000,
    stardust: 2480,
    streak: 6,
    power: 94,
    hp: 1280,
    seasonRole: "Genesis",
    genesisNumber: 14,
  },
  vibe: {
    title: "Dark Moon Surge",
    text: "Your Scorpio instincts are sharp today. Play aggressive, trust your reads, and strike before your rival adapts.",
    quote: "The stars reward the one who moves without hesitation.",
    crushEnergy: "Magnetic",
  },
  arena: {
    status: "1 open challenge waiting",
    opponent: "Solaris IX",
    bet: 120,
    mode: "Ranked Arena",
  },
  stats: {
    wins: 41,
    losses: 18,
    critRate: "18%",
    blockRate: "11%",
  },
  extras: {
    rank: "#27",
    recruits: 14,
    earnings: 350,
  },
};

export const profileMock = {
  player: {
    name: "Aether Fang",
    zodiac: "Scorpio",
    archetype: "Shadow Duelist",
    rarity: "Mythic",
    level: 12,
    xp: 780,
    xpToNext: 1000,
    stardust: 2480,
    seasonRole: "Genesis",
    genesisNumber: 14,
  },
  traits: [
    { name: "Instinct", points: 22 },
    { name: "Aggression", points: 18 },
    { name: "Mystique", points: 20 },
    { name: "Resilience", points: 16 },
    { name: "Precision", points: 18 },
  ],
};

export const cardsMock = {
  featured: {
    id: "origin-001",
    name: "Aether Fang",
    zodiac: "Scorpio",
    archetype: "Shadow Duelist",
    rarity: "Mythic",
    level: 12,
    power: 94,
    status: "Origin Card",
  },
  collection: [
    {
      id: "origin-001",
      name: "Aether Fang",
      zodiac: "Scorpio",
      archetype: "Shadow Duelist",
      rarity: "Mythic",
      level: 12,
      power: 94,
      owned: true,
    },
    {
      id: "card-002",
      name: "Solaris Vow",
      zodiac: "Leo",
      archetype: "Sun Striker",
      rarity: "Epic",
      level: 8,
      power: 71,
      owned: true,
    },
    {
      id: "card-003",
      name: "Luna Veil",
      zodiac: "Pisces",
      archetype: "Dream Weaver",
      rarity: "Rare",
      level: 6,
      power: 59,
      owned: true,
    },
    {
      id: "card-004",
      name: "Volt Reign",
      zodiac: "Aquarius",
      archetype: "Storm Hacker",
      rarity: "Epic",
      level: 9,
      power: 76,
      owned: false,
    },
    {
      id: "card-005",
      name: "Ember Crest",
      zodiac: "Aries",
      archetype: "Blaze Raider",
      rarity: "Rare",
      level: 7,
      power: 63,
      owned: false,
    },
    {
      id: "card-006",
      name: "Verdant Hex",
      zodiac: "Virgo",
      archetype: "Nature Tactician",
      rarity: "Common",
      level: 4,
      power: 42,
      owned: false,
    },
  ],
};

export const leaderboardMock = [
  {
    rank: 1,
    name: "Solaris IX",
    zodiac: "Leo",
    archetype: "Sun Striker",
    rarity: "Mythic",
    level: 18,
    wins: 87,
    battles: 121,
    streak: 9,
    seasonRole: "Genesis",
    genesisNumber: 3,
  },
  {
    rank: 2,
    name: "Aether Fang",
    zodiac: "Scorpio",
    archetype: "Shadow Duelist",
    rarity: "Mythic",
    level: 12,
    wins: 41,
    battles: 59,
    streak: 6,
    seasonRole: "Genesis",
    genesisNumber: 14,
  },
  {
    rank: 3,
    name: "Luna Veil",
    zodiac: "Pisces",
    archetype: "Dream Weaver",
    rarity: "Epic",
    level: 15,
    wins: 64,
    battles: 96,
    streak: 4,
    seasonRole: "Pioneer",
    genesisNumber: null,
  },
  {
    rank: 4,
    name: "Volt Reign",
    zodiac: "Aquarius",
    archetype: "Storm Hacker",
    rarity: "Epic",
    level: 13,
    wins: 52,
    battles: 80,
    streak: 2,
    seasonRole: "Pioneer",
    genesisNumber: null,
  },
  {
    rank: 5,
    name: "Ember Crest",
    zodiac: "Aries",
    archetype: "Blaze Raider",
    rarity: "Rare",
    level: 11,
    wins: 37,
    battles: 60,
    streak: 3,
    seasonRole: "Pioneer",
    genesisNumber: null,
  },
  {
    rank: 6,
    name: "Verdant Hex",
    zodiac: "Virgo",
    archetype: "Nature Tactician",
    rarity: "Rare",
    level: 10,
    wins: 31,
    battles: 54,
    streak: 1,
    seasonRole: "Pioneer",
    genesisNumber: null,
  },
];

export const arenaMock = {
  activeChallenge: {
    status: "Challenge Ready",
    mode: "Ranked Arena",
    opponent: "Solaris IX",
    opponentZodiac: "Leo",
    opponentArchetype: "Sun Striker",
    wager: 120,
    streakRisk: "6 Win Streak",
  },
  quickActions: [
    {
      title: "Enter Ranked",
      subtitle: "Fight for streak and ladder position",
      value: "High Stakes",
    },
    {
      title: "Friendly Duel",
      subtitle: "Low pressure match for testing builds",
      value: "Casual",
    },
    {
      title: "View Challenges",
      subtitle: "Check incoming and pending fight requests",
      value: "2 Pending",
    },
  ],
  recentBattles: [
    {
      opponent: "Luna Veil",
      result: "Win",
      wager: 90,
      mode: "Ranked",
    },
    {
      opponent: "Volt Reign",
      result: "Loss",
      wager: 120,
      mode: "Ranked",
    },
    {
      opponent: "Ember Crest",
      result: "Win",
      wager: 75,
      mode: "Friendly",
    },
  ],
};